server:
  port: 9091

spring:
  profiles:
    active: dev

  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca
    username: biblioteca
    password: pass_db_biblioteca
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always  # Asegura que los scripts SQL se ejecuten
    schema: classpath:schema.sql  # Opcional, si tienes un archivo schema.sql
    data: classpath:data.sql      # Asegura que data.sql se ejecute

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect